#!/bin/bash
#SBATCH --job-name=GammaCorsika
#SBATCH --output=/hkfs/work/workspace/scratch/rn8463-gamma-corsika/log//log%j.out
#SBATCH --error=/hkfs/work/workspace/scratch/rn8463-gamma-corsika/log//log%j.err
#SBATCH --nodes=1
#SBATCH --time=3-00:00:00
#SBATCH --tasks=2
#SBATCH --mem=200gb
#SBATCH --export=NONE
#######################SBATCH --gres=gpu:4

/home/hk-project-pevradio/rn8463/simulations_scripts/corsikaSim.sh