#!/bin/bash
#SBATCH --job-name=ProtonDetectorResponse
#SBATCH --output=/home/hk-project-pevradio/rn8463/log/logDetProton/%j.out
#SBATCH --error=/home/hk-project-pevradio/rn8463/log/logDetProton/%j.err
#SBATCH --nodes=1
#SBATCH --time=2-00:00:00
#SBATCH --mem=200gb
#SBATCH --export=NONE

cp -r $HOME/cvmfsexec/ /scratch/slurm_tmpdir/job_${SLURM_JOB_ID}/
/scratch/slurm_tmpdir/job_${SLURM_JOB_ID}/cvmfsexec icecube.opensciencegrid.org -- /bin/bash /home/hk-project-pevradio/rn8463/simulations_scripts/detectorResponse.sh
