#!/bin/bash
#SBATCH --job-name=mpi
#SBATCH --output=/home/hk-project-radiohfi/bg5912/work/sims/GRAND/lukas/logs/_log%j.out
#SBATCH --error=/home/hk-project-radiohfi/bg5912/work/sims/GRAND/lukas/logs/_log%j.err
#SBATCH --nodes=2
#SBATCH --cpus-per-task=12
#SBATCH --time=00:30:00
#SBATCH --tasks=2
######SBATCH --mem=50gb
######SBATCH --export=NONE
#######################SBATCH --gres=gpu:4

/home/hk-project-radiohfi/bg5912/Horeka/corsikaSim.sh
